version: '3'

services:
  server:
    build: .
    image: server:latest
    ports:
      - "3400:3400"

  neo4j:
    image: neo4j:4.2
    volumes:
      - ./data:/var/lib/neo4j/import
    environment:
      NEO4J_AUTH: "neo4j/test"
    ports:
      - "7474:7474"
      - "7687:7687"
