version: '3.8'

services:
  neo4j:
    image: neo4j:4.1
    volumes:
      - ./neo4j_data:/var/lib/neo4j/import
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_security_procedures_whitelist=apoc.*,gds.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4J_AUTH=neo4j/foxino
      - NEO4J_HEAP_MEMORY=4G
      - NEO4J_CACHE_MEMORY=2G
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - "7474:7474"
      - "7687:7687"
volumes:
  neo4j_data:
